namePrefix: qa-
commonAnnotations:
  note: Hello, I am qa!
resources:
- ../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    org: acmeCorporation
    variant: qa
patches:
- path: map.yaml
