namePrefix: staging-
commonAnnotations:
  note: Hello, I am staging!
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    org: acmeCorporation
    variant: staging
patches:
- path: map.yaml
