namePrefix: production-
commonAnnotations:
  note: Hello, I am production4!
resources:
- ../staging/base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    org: acmeCorporation
    variant: production
patches:
- path: deployment.yaml
